/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package traductor_torrado.vergara;

import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Torrado'sLaptop
 */
public class Traductor extends javax.swing.JFrame {

    /**
     * Creates new form Traductor
     */
    public Traductor() {
        initComponents();
        DefaultListModel modelIdiomas = new DefaultListModel();
        DefaultListModel modelPalabras = new DefaultListModel();
        ptr = null;
    }
    
    Nodo ptr;
    
    class Nodo{
        String Idiomas;
        Nodo linkIdiomas;
        NodoP linkPalabra;
    }
    
    class NodoP{
        String Palabras;
        NodoP linkPalabra;
    }
    
    Nodo addcola(Nodo ptr, String Idio){
        Nodo p = ptr;
        Nodo q = new Nodo();
        q.Idiomas = Idio;
        if(ptr == null){
            ptr = q;
        }else{
            while(p.linkIdiomas!=null){
                p = p.linkIdiomas;
            }
            p.linkIdiomas = q;
        }
        return ptr;
    }
    Nodo BuscaIdiomas(Nodo ptr, String IdiomaB){
        Nodo p = ptr;
        while(p.linkIdiomas!=null && !p.Idiomas.equalsIgnoreCase(IdiomaB)){
            p = p.linkIdiomas;
        }
        if(!p.Idiomas.equals(IdiomaB)){
            JOptionPane.showMessageDialog(null, "No se encontro el idioma");
        }
        return p;
    }
    
    void BuscaPalabras(String word, String IdiomaB){
        Nodo p = ptr;
        BuscaIdiomas(p, IdiomaB);
    }
    
    

    void TranslateWord(Nodo ptr, String IdiomaO, String IdiomaD, String word){
        Nodo p = ptr;
        int cont=0,i=0;
        while(p != null && !p.Idiomas.equals(IdiomaO)){
            p=p.linkIdiomas;
        }
        if(p!=null){
            if(p.Idiomas.equals(IdiomaO)){
                if(p.linkPalabra != null){
                    NodoP q = p.linkPalabra;
                    while(q != null && !q.Palabras.equals(word)){
                        q = q.linkPalabra;
                        cont=cont+1;
                    }
                    if(q!=null && q.Palabras.equals(word)){
                        Nodo pp = ptr;
                        while(pp != null && !pp.Idiomas.equals(IdiomaD)){
                            pp=pp.linkIdiomas;
                        }
                        if(pp!=null && pp.Idiomas.equals(IdiomaD)){
                            NodoP qq = pp.linkPalabra;
                            while(i!=cont){
                                qq=qq.linkPalabra;
                                i=i+1;
                            }
                            System.out.println(qq.Palabras);
                            TraduccionTxt1.setText(qq.Palabras);
                        }else{
                           JOptionPane.showInputDialog(null, "No se encuentra el idioma al que se desea traducir"); 
                        }
                    }else{
                           JOptionPane.showInputDialog(null, "No se encuentra la palabra que se desea traducir"); 
                    }
                }else{
                    JOptionPane.showInputDialog(null, "No hay palabras registradas para ese idioma");
                }    
            }else{
                   JOptionPane.showInputDialog(null, "No se encuentra el idioma de origen de la palabra"); 
            }
        }
    }
    
    void EliminarPalabra(Nodo ptr, String word, String Idioma){
        Nodo p = ptr;
        while(p.linkIdiomas!=null && !p.Idiomas.equalsIgnoreCase(Idioma)){
            p = p.linkIdiomas;
        }
        if(p.linkPalabra!=null){
            NodoP anteQ = null;
            NodoP q = p.linkPalabra;
            while(q!=null && !q.Palabras.equals(word)){
                anteQ = q;
                q = q.linkPalabra;
            }
            if(q!=null && anteQ==null){
                p.linkPalabra=q.linkPalabra;
            }
        }

    }    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Menu = new javax.swing.JFrame();
        Title1 = new javax.swing.JLabel();
        AddSpaTxt1 = new javax.swing.JTextField();
        AddEngTxt1 = new javax.swing.JTextField();
        AddFreTxt1 = new javax.swing.JTextField();
        AddItaTxt1 = new javax.swing.JTextField();
        AddSpaBtn1 = new javax.swing.JButton();
        AddEngBtn1 = new javax.swing.JButton();
        AddFraBtn1 = new javax.swing.JButton();
        AddItaBtn1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        TranslateTxt1 = new javax.swing.JTextField();
        IdiomaOrigenBtn1 = new javax.swing.JComboBox<>();
        IdiomaDestinoBtn1 = new javax.swing.JComboBox<>();
        TraduccionTxt1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        ElimBtn2 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        TranslateBtn = new javax.swing.JButton();
        JLabel = new javax.swing.JLabel();
        GeneradorBtn = new javax.swing.JButton();

        Menu.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Title1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        Title1.setText("Traductor");
        Title1.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        AddSpaTxt1.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

        AddEngTxt1.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

        AddFreTxt1.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        AddFreTxt1.setText(" ");
        AddFreTxt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddFreTxt1ActionPerformed(evt);
            }
        });

        AddItaTxt1.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

        AddSpaBtn1.setFont(new java.awt.Font("Verdana", 2, 11)); // NOI18N
        AddSpaBtn1.setText("Agregar");
        AddSpaBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddSpaBtn1ActionPerformed(evt);
            }
        });

        AddEngBtn1.setFont(new java.awt.Font("Verdana", 2, 11)); // NOI18N
        AddEngBtn1.setText("Add");
        AddEngBtn1.setToolTipText("");
        AddEngBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddEngBtn1ActionPerformed(evt);
            }
        });

        AddFraBtn1.setFont(new java.awt.Font("Verdana", 2, 11)); // NOI18N
        AddFraBtn1.setText("Ajouter");
        AddFraBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddFraBtn1ActionPerformed(evt);
            }
        });

        AddItaBtn1.setFont(new java.awt.Font("Verdana", 2, 11)); // NOI18N
        AddItaBtn1.setText("Inserisci");
        AddItaBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddItaBtn1ActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jLabel8.setText("Consultar Palabras:");

        TranslateTxt1.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

        IdiomaOrigenBtn1.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        IdiomaOrigenBtn1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Espanol", "Ingles", "Frances", "Italiano" }));
        IdiomaOrigenBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IdiomaOrigenBtn1ActionPerformed(evt);
            }
        });

        IdiomaDestinoBtn1.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        IdiomaDestinoBtn1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Espanol", "Ingles", "Frances", "Italiano" }));
        IdiomaDestinoBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IdiomaDestinoBtn1ActionPerformed(evt);
            }
        });

        TraduccionTxt1.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        jLabel9.setText("Eliminar Palabras:");

        jTextField2.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        ElimBtn2.setFont(new java.awt.Font("Verdana", 2, 11)); // NOI18N
        ElimBtn2.setText("Eliminar");
        ElimBtn2.setToolTipText("");

        jLabel10.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jLabel10.setText("Ingles:");

        jLabel11.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jLabel11.setText("Español:");

        jLabel12.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jLabel12.setText("Frances:");

        jLabel13.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jLabel13.setText("Italiano:");

        jLabel14.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jLabel14.setText("Agregar Palabras:");

        TranslateBtn.setFont(new java.awt.Font("Verdana", 2, 12)); // NOI18N
        TranslateBtn.setText("Traducir");
        TranslateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TranslateBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MenuLayout = new javax.swing.GroupLayout(Menu.getContentPane());
        Menu.getContentPane().setLayout(MenuLayout);
        MenuLayout.setHorizontalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MenuLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Title1)
                .addGap(225, 225, 225))
            .addGroup(MenuLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MenuLayout.createSequentialGroup()
                        .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(MenuLayout.createSequentialGroup()
                                    .addComponent(jLabel11)
                                    .addGap(97, 97, 97)
                                    .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(AddEngBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(AddEngTxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel10)))
                                .addGroup(MenuLayout.createSequentialGroup()
                                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(ElimBtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(MenuLayout.createSequentialGroup()
                                    .addComponent(TranslateTxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(44, 44, 44)
                                    .addComponent(IdiomaOrigenBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(AddSpaTxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(AddSpaBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                        .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MenuLayout.createSequentialGroup()
                                .addComponent(IdiomaDestinoBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(17, 17, 17))
                            .addComponent(AddFreTxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AddFraBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addGap(22, 22, 22)
                        .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AddItaTxt1)
                            .addComponent(TraduccionTxt1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(AddItaBtn1, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE))
                        .addContainerGap(41, Short.MAX_VALUE))
                    .addGroup(MenuLayout.createSequentialGroup()
                        .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addGroup(MenuLayout.createSequentialGroup()
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(116, 116, 116)
                                .addComponent(TranslateBtn)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        MenuLayout.setVerticalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Title1)
                .addGap(21, 21, 21)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13))
                .addGap(7, 7, 7)
                .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddSpaTxt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AddEngTxt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AddFreTxt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AddItaTxt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddSpaBtn1)
                    .addComponent(AddEngBtn1)
                    .addComponent(AddFraBtn1)
                    .addComponent(AddItaBtn1))
                .addGap(15, 15, 15)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MenuLayout.createSequentialGroup()
                        .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TranslateTxt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(IdiomaOrigenBtn1)
                            .addComponent(IdiomaDestinoBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(MenuLayout.createSequentialGroup()
                                .addGap(0, 21, Short.MAX_VALUE)
                                .addComponent(jLabel9))
                            .addGroup(MenuLayout.createSequentialGroup()
                                .addComponent(TranslateBtn)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(MenuLayout.createSequentialGroup()
                        .addComponent(TraduccionTxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ElimBtn2))
                .addGap(24, 24, 24))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JLabel.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        JLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLabel.setText("Bienvenido al traductor");

        GeneradorBtn.setFont(new java.awt.Font("Verdana", 2, 12)); // NOI18N
        GeneradorBtn.setText("Continuar-Continue-Continuer-Continua");
        GeneradorBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GeneradorBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(86, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(JLabel)
                        .addGap(79, 79, 79))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(GeneradorBtn)
                        .addGap(71, 71, 71))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(JLabel)
                .addGap(45, 45, 45)
                .addComponent(GeneradorBtn)
                .addContainerGap(156, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddFreTxt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddFreTxt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddFreTxt1ActionPerformed

    private void AddSpaBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddSpaBtn1ActionPerformed
        String Idioma = "Espanol";
        String Palabra = AddSpaTxt1.getText();
        if(!Idioma.isEmpty() && !Palabra.isEmpty()){
            Nodo p = ptr;
            while(p != null){
                if(p.Idiomas.equals(Idioma)){
                    NodoP q = new NodoP();
                    q.Palabras = Palabra;
                    q.linkPalabra = p.linkPalabra;
                    p.linkPalabra = q;
                    break;
                }
                p = p.linkIdiomas;
            }
        }
    }//GEN-LAST:event_AddSpaBtn1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void GeneradorBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GeneradorBtnActionPerformed
        ptr = addcola(ptr, "Espanol");
        ptr = addcola(ptr, "Ingles");
        ptr = addcola(ptr, "Frances");
        ptr = addcola (ptr, "Italiano");
        Menu.setVisible(true);
        Menu.setBounds(300, 300, 563, 365);    
    }//GEN-LAST:event_GeneradorBtnActionPerformed

    private void AddEngBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddEngBtn1ActionPerformed
        String Idioma = "Ingles";
        String Palabra = AddEngTxt1.getText();
        if(!Idioma.isEmpty() && !Palabra.isEmpty()){
            Nodo p = ptr;
            while(p != null){
                if(p.Idiomas.equals(Idioma)){
                    NodoP q = new NodoP();
                    q.Palabras = Palabra;
                    q.linkPalabra = p.linkPalabra;
                    p.linkPalabra = q;
                    break;
                }
                p = p.linkIdiomas;
            }
        }
    }//GEN-LAST:event_AddEngBtn1ActionPerformed

    private void AddFraBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddFraBtn1ActionPerformed
        String Idioma = "Frances";
        String Palabra = AddFreTxt1.getText();
        if(!Idioma.isEmpty() && !Palabra.isEmpty()){
            Nodo p = ptr;
            while(p != null){
                if(p.Idiomas.equals(Idioma)){
                    NodoP q = new NodoP();
                    q.Palabras = Palabra;
                    q.linkPalabra = p.linkPalabra;
                    p.linkPalabra = q;
                    break;
                }
                p = p.linkIdiomas;
            }
        }
    }//GEN-LAST:event_AddFraBtn1ActionPerformed

    private void AddItaBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddItaBtn1ActionPerformed
        String Idioma = "Italiano";
        String Palabra = AddItaTxt1.getText();
        if(!Idioma.isEmpty() && !Palabra.isEmpty()){
            Nodo p = ptr;
            while(p != null){
                if(p.Idiomas.equals(Idioma)){
                    NodoP q = new NodoP();
                    q.Palabras = Palabra;
                    q.linkPalabra = p.linkPalabra;
                    p.linkPalabra = q;
                    break;
                }
                p = p.linkIdiomas;
            }
        }
    }//GEN-LAST:event_AddItaBtn1ActionPerformed

    private void IdiomaOrigenBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IdiomaOrigenBtn1ActionPerformed
       
    }//GEN-LAST:event_IdiomaOrigenBtn1ActionPerformed

    private void IdiomaDestinoBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IdiomaDestinoBtn1ActionPerformed
    
    }//GEN-LAST:event_IdiomaDestinoBtn1ActionPerformed

    private void TranslateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TranslateBtnActionPerformed
         String IdiomaOri = IdiomaOrigenBtn1.getSelectedItem().toString();
         String IdiomaDest = IdiomaDestinoBtn1.getSelectedItem().toString();
         System.out.println(IdiomaOri);
         System.out.println(IdiomaDest);
         String w = TranslateTxt1.getText();
         TranslateWord(ptr, IdiomaOri,IdiomaDest,w);
    }//GEN-LAST:event_TranslateBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Traductor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Traductor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Traductor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Traductor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Traductor().setVisible(true);
            }
        });
    }
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddEngBtn1;
    private javax.swing.JTextField AddEngTxt1;
    private javax.swing.JButton AddFraBtn1;
    private javax.swing.JTextField AddFreTxt1;
    private javax.swing.JButton AddItaBtn1;
    private javax.swing.JTextField AddItaTxt1;
    private javax.swing.JButton AddSpaBtn1;
    private javax.swing.JTextField AddSpaTxt1;
    private javax.swing.JButton ElimBtn2;
    private javax.swing.JButton GeneradorBtn;
    private javax.swing.JComboBox<String> IdiomaDestinoBtn1;
    private javax.swing.JComboBox<String> IdiomaOrigenBtn1;
    private javax.swing.JLabel JLabel;
    private javax.swing.JFrame Menu;
    private javax.swing.JLabel Title1;
    private javax.swing.JLabel TraduccionTxt1;
    private javax.swing.JButton TranslateBtn;
    private javax.swing.JTextField TranslateTxt1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
